title: "Equitable Healthcare AI: From Algorithms to Clinical Impact"
description: "A Comprehensive, Self-Updating Technical and Practical Textbook"
author: "Sanjay Basu, MD PhD"
email: "sanjay.basu@waymarkcare.com"
baseurl: "/healthcare-ai-equity"
url: "https://sanjaybasu.github.io"

markdown: kramdown
theme: minima

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  chapters:
    output: true
    permalink: /chapters/:name/

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
