name: Manual Literature Update

on:
  workflow_dispatch:
    inputs:
      date_range:
        description: 'Number of days to search back'
        required: true
        default: '7'
        type: choice
        options:
          - '1'
          - '7'
          - '14'
          - '30'
      specific_chapter:
        description: 'Update specific chapter (leave empty for all)'
        required: false
        type: string
      dry_run:
        description: 'Dry run (no PR created)'
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  manual-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run manual update
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
        run: |
          python scripts/search_literature.py --date-range ${{ inputs.date_range }}
          python scripts/assess_relevance.py
          python scripts/update_chapters.py --dry-run ${{ inputs.dry_run }}
      
      - name: Display results
        run: |
          echo "## Manual Update Results" >> $GITHUB_STEP_SUMMARY
          echo "- Date range: ${{ inputs.date_range }} days" >> $GITHUB_STEP_SUMMARY
          echo "- Dry run: ${{ inputs.dry_run }}" >> $GITHUB_STEP_SUMMARY
          if [ -f data/update_summary.json ]; then
            cat data/update_summary.json >> $GITHUB_STEP_SUMMARY
          fi
